use crate::constants::map_ids;

/// Represents a teleport destination in Bloodborne
#[derive(Debug, Clone, PartialEq)]
pub struct Location {
    pub name: &'static str,
    pub region: &'static str,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub map_id: [u8; 4],
}

/// All available teleport locations
pub const LOCATIONS: [Location; 44] = [
    // Hunter's Dream
    Location {
        name: "Hunter's Dream",
        region: "Hunter's Dream",
        x: -8.0,
        y: -6.0,
        z: -18.0,
        map_id: map_ids::HUNTERS_DREAM,
    },
    // Yharnam Headstone
    Location {
        name: "1st Floor Sickroom",
        region: "Yharnam Headstone",
        x: -199.74,
        y: -50.759,
        z: 179.42,
        map_id: map_ids::CENTRAL_YHARNAM_1,
    },
    Location {
        name: "Central Yharnam",
        region: "Yharnam Headstone",
        x: -193.4,
        y: -28.646,
        z: 68.5,
        map_id: map_ids::CENTRAL_YHARNAM_1,
    },
    Location {
        name: "Great Bridge",
        region: "Yharnam Headstone",
        x: -124.488,
        y: -27.021,
        z: 64.673,
        map_id: map_ids::CENTRAL_YHARNAM_1,
    },
    Location {
        name: "Tomb of Oedon",
        region: "Yharnam Headstone",
        x: -33.811,
        y: -40.722,
        z: 87.303,
        map_id: map_ids::CENTRAL_YHARNAM_1,
    },
    Location {
        name: "Cathedral Ward",
        region: "Yharnam Headstone",
        x: 16.775,
        y: -9.511,
        z: 103.27,
        map_id: map_ids::CENTRAL_YHARNAM_0,
    },
    Location {
        name: "Grand Cathedral Ward",
        region: "Yharnam Headstone",
        x: 67.808,
        y: 35.713,
        z: 339.689,
        map_id: map_ids::CENTRAL_YHARNAM_0,
    },
    Location {
        name: "Upper Cathedral Ward",
        region: "Yharnam Headstone",
        x: -24.643,
        y: 40.621,
        z: 250.57,
        map_id: map_ids::CENTRAL_YHARNAM_2,
    },
    Location {
        name: "Lumenflower Gardens",
        region: "Yharnam Headstone",
        x: 45.335,
        y: 51.403,
        z: 300.35,
        map_id: map_ids::CENTRAL_YHARNAM_2,
    },
    Location {
        name: "Altar of Despair",
        region: "Yharnam Headstone",
        x: 114.86,
        y: 4.443,
        z: 425.02,
        map_id: map_ids::CENTRAL_YHARNAM_2,
    },
    Location {
        name: "Old Yharnam",
        region: "Yharnam Headstone",
        x: 126.4,
        y: -65.214,
        z: 36.0,
        map_id: map_ids::OLD_YHARNAM_0,
    },
    Location {
        name: "Church of the Good Chalice",
        region: "Yharnam Headstone",
        x: -139.979,
        y: -126.664,
        z: 57.359,
        map_id: map_ids::OLD_YHARNAM_0,
    },
    Location {
        name: "Graveyard of the Darkbeast",
        region: "Yharnam Headstone",
        x: 111.86,
        y: -120.783,
        z: -65.249,
        map_id: map_ids::OLD_YHARNAM_0,
    },
    // Frontier Headstone
    Location {
        name: "Hemwick Charnel Lane",
        region: "Frontier Headstone",
        x: -172.0,
        y: -22.0,
        z: 485.5,
        map_id: map_ids::HEMWICK_0,
    },
    Location {
        name: "Witch's Abode",
        region: "Frontier Headstone",
        x: -336.3,
        y: 2.4,
        z: 733.0,
        map_id: map_ids::HEMWICK_0,
    },
    Location {
        name: "Forbidden Woods",
        region: "Frontier Headstone",
        x: -190.0,
        y: -76.3,
        z: 252.0,
        map_id: map_ids::FORBIDDEN_WOODS_0,
    },
    Location {
        name: "Forbidden Grave",
        region: "Frontier Headstone",
        x: -335.0,
        y: -186.5,
        z: 479.0,
        map_id: map_ids::FORBIDDEN_WOODS_0,
    },
    Location {
        name: "Byrgenwerth",
        region: "Frontier Headstone",
        x: -400.4,
        y: -180.8,
        z: 414.6,
        map_id: map_ids::BYRGENWERTH_0,
    },
    Location {
        name: "Moonside Lake",
        region: "Frontier Headstone",
        x: -509.0,
        y: -271.0,
        z: 371.0,
        map_id: map_ids::BYRGENWERTH_2,
    },
    // Unseen Headstone
    Location {
        name: "Yahar'gul, Unseen Village",
        region: "Unseen Headstone",
        x: 257.4,
        y: -51.4,
        z: 70.0,
        map_id: map_ids::YAHARGUL_0,
    },
    Location {
        name: "Yahar'gul Chapel",
        region: "Unseen Headstone",
        x: 260.4,
        y: -88.0,
        z: -55.6,
        map_id: map_ids::YAHARGUL_0,
    },
    Location {
        name: "Advent Plaza",
        region: "Unseen Headstone",
        x: 418.8,
        y: -123.6,
        z: -253.4,
        map_id: map_ids::YAHARGUL_0,
    },
    Location {
        name: "Hypogean Gaol",
        region: "Unseen Headstone",
        x: 219.6,
        y: -97.6,
        z: -78.8,
        map_id: map_ids::YAHARGUL_0,
    },
    Location {
        name: "Forsaken Castle Cainhurst",
        region: "Unseen Headstone",
        x: -4.5,
        y: 33.8,
        z: -187.9,
        map_id: map_ids::CAINHURST_0,
    },
    Location {
        name: "Logarius' Seat",
        region: "Unseen Headstone",
        x: 47.8,
        y: 111.8,
        z: -350.4,
        map_id: map_ids::CAINHURST_0,
    },
    Location {
        name: "Vileblood Queen's Chamber",
        region: "Unseen Headstone",
        x: 122.4,
        y: 129.0,
        z: -455.0,
        map_id: map_ids::CAINHURST_0,
    },
    Location {
        name: "Abandoned Old Workshop",
        region: "Unseen Headstone",
        x: 129.8,
        y: -19.9,
        z: 140.8,
        map_id: map_ids::ABANDONED_WORKSHOP_1,
    },
    // Nightmare Headstone
    Location {
        name: "Lecture Building",
        region: "Nightmare Headstone",
        x: -472.37,
        y: -185.25,
        z: 594.9,
        map_id: map_ids::BYRGENWERTH_0,
    },
    Location {
        name: "Lecture Building 2nd Floor",
        region: "Nightmare Headstone",
        x: -444.22,
        y: -177.25,
        z: 514.19,
        map_id: map_ids::BYRGENWERTH_0,
    },
    Location {
        name: "Nightmare Frontier",
        region: "Nightmare Headstone",
        x: 0.35,
        y: 1500.0,
        z: 0.0,
        map_id: map_ids::NIGHTMARE_FRONTIER_0,
    },
    Location {
        name: "Nightmare of Mensis",
        region: "Nightmare Headstone",
        x: -104.65,
        y: 1462.28,
        z: -42.65,
        map_id: map_ids::NIGHTMARE_FRONTIER_0,
    },
    Location {
        name: "Mergo's Loft: Base",
        region: "Nightmare Headstone",
        x: 84.58,
        y: 986.7,
        z: -0.37,
        map_id: map_ids::MERGOS_LOFT_0,
    },
    Location {
        name: "Mergo's Loft: Middle",
        region: "Nightmare Headstone",
        x: 136.69,
        y: 1061.26,
        z: -14.86,
        map_id: map_ids::MERGOS_LOFT_0,
    },
    Location {
        name: "Wet Nurse's Lunarium",
        region: "Nightmare Headstone",
        x: 140.72,
        y: 1124.3,
        z: -37.98,
        map_id: map_ids::MERGOS_LOFT_0,
    },
    // Hunter's Nightmare Headstone
    Location {
        name: "Hunter's Nightmare",
        region: "Hunter's Nightmare Headstone",
        x: -481.68,
        y: 1490.49,
        z: -497.73,
        map_id: map_ids::HUNTERS_NIGHTMARE_0,
    },
    Location {
        name: "Nightmare Church",
        region: "Hunter's Nightmare Headstone",
        x: -434.08,
        y: 1503.18,
        z: -594.52,
        map_id: map_ids::HUNTERS_NIGHTMARE_0,
    },
    Location {
        name: "Nightmare Grand Cathedral",
        region: "Hunter's Nightmare Headstone",
        x: -433.09,
        y: 1535.71,
        z: -261.57,
        map_id: map_ids::HUNTERS_NIGHTMARE_0,
    },
    Location {
        name: "Underground Corpse Pile",
        region: "Hunter's Nightmare Headstone",
        x: -406.81,
        y: 1503.79,
        z: -743.0,
        map_id: map_ids::HUNTERS_NIGHTMARE_0,
    },
    Location {
        name: "Research Hall",
        region: "Hunter's Nightmare Headstone",
        x: -318.67,
        y: 1553.02,
        z: -824.22,
        map_id: map_ids::RESEARCH_HALL_0,
    },
    Location {
        name: "Lumenwood Garden",
        region: "Hunter's Nightmare Headstone",
        x: -432.15,
        y: 1593.0,
        z: -824.37,
        map_id: map_ids::RESEARCH_HALL_0,
    },
    Location {
        name: "Astral Clocktower",
        region: "Hunter's Nightmare Headstone",
        x: -454.88,
        y: 1595.57,
        z: -824.44,
        map_id: map_ids::RESEARCH_HALL_0,
    },
    Location {
        name: "Fishing Hamlet",
        region: "Hunter's Nightmare Headstone",
        x: -619.2,
        y: 1594.3,
        z: -817.2,
        map_id: map_ids::FISHING_HAMLET_0,
    },
    Location {
        name: "Lighthouse Hut",
        region: "Hunter's Nightmare Headstone",
        x: -645.2,
        y: 1614.66,
        z: -867.2,
        map_id: map_ids::FISHING_HAMLET_0,
    },
    Location {
        name: "Coast",
        region: "Hunter's Nightmare Headstone",
        x: -695.2,
        y: 1577.27,
        z: -943.2,
        map_id: map_ids::FISHING_HAMLET_0,
    },
];

/// Get locations grouped by region
pub fn get_locations_by_region() -> Vec<(&'static str, Vec<&'static Location>)> {
    let mut regions: Vec<(&'static str, Vec<&'static Location>)> = Vec::new();
    for location in &LOCATIONS {
        if let Some(existing) = regions
            .iter_mut()
            .find(|(name, _)| *name == location.region)
        {
            existing.1.push(location);
        } else {
            regions.push((location.region, vec![location]));
        }
    }
    regions
}
